### ISSUE TITLE
Why not Twisted?

### ISSUE THREAD

**Issue by jgupta** [couchbaselabs/couchbase-python-cffi#1]
Why Twisted will not be supported by this module?
Will installing this module break Twisted?

PyPy supports Twisted.

**Comment by ronreiter** [comment]
Yeah, I would like to know why as well. Thanks

**Comment by mnunberg** [comment]
This module will not break twisted. However, the twisted support planned for the next release of the mainline client (i.e. https://github.com/couchbase/couchbase-python-client) will not work on PyPy at the moment.

**Comment by mnunberg** [comment]
There is experimental twisted support in the 2.x branch. I currently don't know if it will build with currently available packages, but it is in the works...
